### ISSUE TITLE
How would it work on an account with 100,000 bookmarks

### ISSUE THREAD

**Issue by nikitavoloboev** [prinsss/twitter-web-exporter#51]
From what I see in readme, in order for me to get the 100k bookmarks it would have to manually scroll through the https://x.com/i/bookmarks page? But that would take forever, no?

**Comment by nikitavoloboev** [comment]
Also I want to be able to export all the bookmarks from my X account and delete them after this.

**Comment by prinsss** [comment]
Due to the nature of this script, yes.

In order to export that amount of bookmarks, you need to scroll through the bookmarks page for a very long time, to make sure that Twitter Web App itself loads enough data. This script does not send any requests to Twitter API, it just captures the data that Twitter Web App has already loaded.

You could use a tool like [AutoScroll](https://chromewebstore.google.com/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan) to automate this process.

> export bookmarks and delete them after this

This is not possible with this script since we do not send network requests. One could fork this script and modify it to automatically click delete buttons, but please be aware that this could potentially violate Twitter's ToS and get your account locked.
